default:
  image: node:20-alpine

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

stages:
  - test
variables:
  JSAU_REPOSITORY_FILE_PATH: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/jsau-data"

tests:
  stage: test
  before_script:
    - mkdir -p jsau-data/html jsau-data/json
    - echo "<html><body>Test File</body></html>" > jsau-data/html/venezuela.html
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test:ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - .npm/
  coverage: /All files[^\|]*\|[^\|]*\s+([\d\.]+)/ 
  only:
    - main